id = "kanagawa-theme"
name = "Kanagawa Themes"
schema_version = 1
version = "0.0.1"
authors = ["Yair Chan <enyaoficial001@gmail.com>"]
description = "ğŸ‰ A theme inspired by the Kanagawa wave ğŸŒŠ"
repository = "https://github.com/IYair/kanagawa-theme.git"
